### ISSUE TITLE
PetDB Statistics Plot needs to include new ECDB statistics

### ISSUE THREAD

**Issue by lulin-song** [iedadata/EarthChemWebServiceAndClient#4]
ECDB is launched to replace the PetDB. Now we have both ECDB and PetDB running at the same time. So their download statistics need to be merged. See the repo https://github.com/iedadata/PetDB ticket https://github.com/iedadata/PetDB/issues/7

**Comment by lulin-song** [comment]
Test view is created. https://test-ecl.earthchem.org/plot/PetDBStatsPlotView.php
Wait Peng to fix the web service to  return correct XML format data.

**Comment by lulin-song** [comment]
Deployed to https://www.iedadata.org/community/usage/ @kelseymarkey  Please check.

**Comment by kelseymarkey** [comment]
Looks great Lulin, thanks @lulin-song and @sparkji !

**Comment by lulin-song** [comment]
Done
